# Generated by Django 5.1.7 on 2025-04-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('promocodes', '0003_alter_promocodes_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_amount', models.FloatField(default=0.0)),
                ('rental_price', models.FloatField(default=0.0)),
                ('rental_days', models.PositiveIntegerField(default=1)),
                ('services_price', models.FloatField(default=0.0)),
                ('total_price', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bookings.booking')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promocodes.promocodes')),
            ],
        ),
    ]
