# Generated by Django 5.1.7 on 2025-04-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_client_alter_booking_property_and_more'),
        ('invoices', '0002_remove_invoice_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='bookings.booking'),
        ),
    ]
