# Generated by Django 5.1.7 on 2025-04-02 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='0000000000', max_length=20)),
                ('street', models.CharField(default='Write your Streetname', max_length=100)),
                ('street_number', models.CharField(default='0000', max_length=10)),
                ('city', models.CharField(default='Write your City', max_length=100)),
                ('country', models.CharField(default='Write your Country', max_length=100)),
                ('postal_code', models.CharField(default='00000', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_filed', models.BooleanField(default=False)),
                ('type', models.CharField(default='person', max_length=20)),
                ('tax_id', models.CharField(default='000000000', max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_auth.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
