# Generated by Django 5.1.7 on 2025-05-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_auth', '0002_alter_profile_address_remove_profile_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lease_auth.userlogo'),
        ),
    ]
