# Generated by Django 5.1.7 on 2025-04-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lease_auth', '0003_logintoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_number',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='data_filed',
            new_name='data_filled',
        ),
    ]
