# Generated by Django 5.1.7 on 2025-04-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocodes',
            old_name='valid_unitil',
            new_name='valid_until',
        ),
    ]
