# Generated by Django 5.1.7 on 2025-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0002_promocodes_active_alter_promocodes_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
