# Generated by Django 5.1.7 on 2025-04-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0002_rename_valid_unitil_promocodes_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodes',
            name='discount_percent',
            field=models.FloatField(default=0.0, verbose_name='discount percent'),
        ),
    ]
