# Generated by Django 5.1.7 on 2025-04-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning')], default='available', max_length=20),
        ),
    ]
