# Generated by Django 5.1.7 on 2025-04-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
