# Generated by Django 5.1.7 on 2025-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_unit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
