# Generated by Django 5.1.7 on 2025-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_unitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='max_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='price_per_extra_person',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
