# Generated by Django 5.1.7 on 2025-04-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_unit_max_capacity_unit_price_per_extra_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='price_per_extra_person',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='price_per_night',
            field=models.FloatField(default=0.0),
        ),
    ]
