# Generated by Django 5.1.7 on 2025-06-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_unit_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='units', to='units.amenity'),
        ),
    ]
