# Generated by Django 5.1.7 on 2025-04-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_alter_unit_price_per_extra_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('house', 'House'), ('studio', 'Studio'), ('suite', 'Suite'), ('cabin', 'Cabin'), ('condo', 'Condo'), ('townhouse', 'Townhouse')], default='apartment', max_length=20),
        ),
    ]
