# Generated by Django 5.1.7 on 2025-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_amenity_unit_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='key',
        ),
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
