# Generated by Django 5.1.7 on 2025-04-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='proertyId',
            new_name='proerty_id',
        ),
    ]
