# Generated by Django 5.1.7 on 2025-04-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_proertyid_service_proerty_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='proerty_id',
            new_name='property_id',
        ),
    ]
