# Generated by Django 5.1.7 on 2025-04-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_proerty_id_service_property_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='property_id',
            new_name='property',
        ),
    ]
