# Generated by Django 5.1.7 on 2025-04-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('clients', '0004_alter_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='addresses.address'),
        ),
    ]
