# Generated by Django 5.1.7 on 2025-04-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='userId',
            new_name='user',
        ),
    ]
