# Generated by Django 5.1.7 on 2025-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='altText',
            new_name='alt_text',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(blank=True, upload_to='property_images/'),
        ),
    ]
