# Generated by Django 5.1.7 on 2025-04-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('properties', '0002_rename_alttext_propertyimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='addresses.address'),
        ),
    ]
