# Generated by Django 5.1.7 on 2025-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_active_alter_propertyimage_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
