# Generated by Django 5.1.7 on 2025-06-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.CharField(default='narnia@dream.com', max_length=255),
        ),
    ]
