amenity_list = [
    {"label": "Double Bed", "category": "Sleeping & Comfort"},
    {"label": "Sofa Bed", "category": "Sleeping & Comfort"},
    {"label": "Single Bed", "category": "Sleeping & Comfort"},
    {"label": "Extra Pillows and Blankets", "category": "Sleeping & Comfort"},
    
    {"label": "Shower", "category": "Bathroom"},
    {"label": "Bathtub", "category": "Bathroom"},
    {"label": "Toilet Paper", "category": "Bathroom"},
    {"label": "Hair Dryer", "category": "Bathroom"},
    {"label": "Towels", "category": "Bathroom"},
    {"label": "Toiletries", "category": "Bathroom"},

    {"label": "Wi-Fi", "category": "Tech & Entertainment"},
    {"label": "TV", "category": "Tech & Entertainment"},
    {"label": "Cable TV", "category": "Tech & Entertainment"},
    {"label": "Smart TV", "category": "Tech & Entertainment"},
    {"label": "Air Conditioning", "category": "Tech & Entertainment"},
    {"label": "Heating", "category": "Tech & Entertainment"},
    {"label": "Bluetooth Speaker", "category": "Tech & Entertainment"},
    {"label": "Workspace", "category": "Tech & Entertainment"},

    {"label": "Kitchen", "category": "Kitchen & Dining"},
    {"label": "Microwave", "category": "Kitchen & Dining"},
    {"label": "Refrigerator", "category": "Kitchen & Dining"},
    {"label": "Oven", "category": "Kitchen & Dining"},
    {"label": "Dishwasher", "category": "Kitchen & Dining"},
    {"label": "Washing Machine", "category": "Kitchen & Dining"},
    {"label": "Dryer", "category": "Kitchen & Dining"},
    {"label": "Toaster", "category": "Kitchen & Dining"},
    {"label": "Coffee Maker", "category": "Kitchen & Dining"},
    {"label": "Kettle", "category": "Kitchen & Dining"},
    {"label": "Cookware", "category": "Kitchen & Dining"},
    {"label": "Dishes & Silverware", "category": "Kitchen & Dining"},
    {"label": "Dining Table", "category": "Kitchen & Dining"},
    {"label": "Dining Chairs", "category": "Kitchen & Dining"},
    {"label": "Dining Set", "category": "Kitchen & Dining"},
    {"label": "Dining Bench", "category": "Kitchen & Dining"},
    
    {"label": "Balcony", "category": "Outdoor"},
    {"label": "Terrace", "category": "Outdoor"},
    {"label": "Garden Access", "category": "Outdoor"},
    {"label": "Outdoor Furniture", "category": "Outdoor"},
]
