# Generated by Django 5.1.7 on 2025-06-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('promocodes', '0001_initial'),
        ('properties', '0001_initial'),
        ('services', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests_count', models.PositiveIntegerField()),
                ('total_price', models.FloatField(default=0.0)),
                ('total_days', models.PositiveIntegerField(default=1)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_amount', models.FloatField(default=0.0)),
                ('base_renting_price', models.FloatField(default=0.0)),
                ('total_services_price', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clients.client')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promocodes.promocodes')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.property')),
                ('services', models.ManyToManyField(blank=True, related_name='bookings', to='services.service')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='units.unit')),
            ],
        ),
    ]
