# Generated by Django 5.1.7 on 2025-04-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0008_rename_userid_client_user'),
        ('promocodes', '0003_alter_promocodes_discount_percent'),
        ('services', '0005_alter_service_price'),
        ('units', '0006_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests_count', models.PositiveIntegerField()),
                ('total_price', models.FloatField(default=0.0)),
                ('total_days', models.PositiveIntegerField(default=1)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_amount', models.FloatField(default=0.0)),
                ('base_renting_price', models.FloatField(default=0.0)),
                ('total_services_price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promocodes.promocodes')),
                ('services', models.ManyToManyField(blank=True, to='services.service')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
        ),
    ]
