# Generated by Django 5.1.7 on 2025-04-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('clients', '0002_client_active'),
        ('properties', '0002_property_active_alter_propertyimage_property'),
        ('units', '0002_alter_unit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='units.unit'),
        ),
    ]
