# Generated by Django 5.1.7 on 2025-04-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='guests_count',
        ),
        migrations.AddField(
            model_name='booking',
            name='base_renting_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_services_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
