# Generated by Django 5.1.7 on 2025-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_client_alter_booking_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
